DROP TABLE IF EXISTS issue_event;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS account;

-- 사용자 테이블
CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR(255) UNIQUE NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         CONSTRAINT account_status_check CHECK (status IN ('ACTIVE', 'DEACTIVATED', 'PENDING_VERIFICATION'))
);

-- 프로젝트 테이블
CREATE TABLE project (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         account_id BIGINT NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         api_key VARCHAR(255) UNIQUE NOT NULL,
                         status VARCHAR(255) NOT NULL DEFAULT 'ACTIVE',
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         CONSTRAINT project_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id),
                         CONSTRAINT project_account_id_name_uq UNIQUE (account_id, name),
                         CONSTRAINT project_status_check CHECK (status IN ('ACTIVE', 'DELETED'))
);

-- 이슈 요약 테이블
CREATE TABLE issue (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       project_id BIGINT NOT NULL,
                       fingerprint VARCHAR(64) NOT NULL,
                       level VARCHAR(255) NOT NULL DEFAULT 'ERROR',
                       message TEXT NOT NULL,
                       stack_trace TEXT,
                       status VARCHAR(255) NOT NULL DEFAULT 'UNHANDLED',
                       event_count BIGINT NOT NULL DEFAULT 1,
                       last_seen TIMESTAMP WITH TIME ZONE NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                       CONSTRAINT issue_project_id_fkey FOREIGN KEY (project_id) REFERENCES project (id),
                       CONSTRAINT issue_project_id_fingerprint_uq UNIQUE (project_id, fingerprint),
                       CONSTRAINT issue_level_check CHECK (level IN ('ERROR', 'WARN', 'INFO', 'DEBUG')),
                       CONSTRAINT issue_status_check CHECK (status IN ('UNHANDLED', 'RESOLVED', 'IGNORED'))
);

-- 개별 에러 이벤트 원본 데이터 테이블
CREATE TABLE issue_event (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             issue_id BIGINT NOT NULL,
                             context_data JSONB,
                             occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                             updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                             CONSTRAINT issue_event_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES issue (id)
);

-- Foreign Key 인덱스 생성 (성능 최적화)
CREATE INDEX project_ix_account_id ON project (account_id);
CREATE INDEX issue_ix_project_id ON issue (project_id);
CREATE INDEX issue_event_ix_issue_id ON issue_event (issue_id);