DROP TABLE IF EXISTS error_event;
DROP TABLE IF EXISTS issue;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS account;

DROP TYPE IF EXISTS issue_status;
DROP TYPE IF EXISTS issue_level;
DROP TYPE IF EXISTS project_status;
DROP TYPE IF EXISTS account_status;

-- 재생성: Enum 타입 정의
CREATE TYPE account_status AS ENUM ('ACTIVE', 'DEACTIVATED', 'PENDING_VERIFICATION');
CREATE TYPE project_status AS ENUM ('ACTIVE', 'DELETED');
CREATE TYPE issue_status AS ENUM ('UNHANDLED', 'RESOLVED', 'IGNORED');
CREATE TYPE issue_level AS ENUM ('ERROR', 'WARN', 'INFO', 'DEBUG');

-- 사용자 테이블
CREATE TABLE account (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         email VARCHAR(255) UNIQUE NOT NULL,
                         password VARCHAR(255) NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         status account_status NOT NULL DEFAULT 'ACTIVE',
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- 프로젝트 테이블
CREATE TABLE project (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         account_id BIGINT NOT NULL,
                         name VARCHAR(100) NOT NULL,
                         api_key VARCHAR(255) UNIQUE NOT NULL,
                         status project_status NOT NULL DEFAULT 'ACTIVE',
                         created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                         updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

                         CONSTRAINT project_account_id_fkey FOREIGN KEY (account_id) REFERENCES account (id),
                         CONSTRAINT project_account_id_name_uq UNIQUE (account_id, name)
);

-- 이슈 요약 테이블
CREATE TABLE issue (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       project_id BIGINT NOT NULL,
                       fingerprint VARCHAR(64) NOT NULL, -- SHA-256 해시 길이에 최적화
                       level issue_level NOT NULL DEFAULT 'ERROR',
                       message TEXT NOT NULL,
                       stack_trace TEXT,
                       status issue_status NOT NULL DEFAULT 'UNHANDLED',
                       event_count BIGINT NOT NULL DEFAULT 1,
                       last_seen TIMESTAMP WITH TIME ZONE NOT NULL,
                       created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                       updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

                       CONSTRAINT issue_project_id_fkey FOREIGN KEY (project_id) REFERENCES project (id),
                       CONSTRAINT issue_project_id_fingerprint_uq UNIQUE (project_id, fingerprint)
);

-- 개별 에러 이벤트 원본 데이터 테이블
CREATE TABLE error_event (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             issue_id BIGINT NOT NULL,
                             occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
                             context_data JSONB,
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),

                             CONSTRAINT error_event_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES issue (id)
);

-- Foreign Key 인덱스 생성 (성능 최적화)
CREATE INDEX project_ix_account_id ON project (account_id);
CREATE INDEX issue_ix_project_id ON issue (project_id);
CREATE INDEX error_event_ix_issue_id ON error_event (issue_id);